### ISSUE TITLE
Pygame event queue full

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/sonic-jump-activity#6]
Resuming an activity instance and the play button doesn't work as expected and this is in the logs:

```
Traceback (most recent call last):
  File "/home/ibiam/Activities/sonic-jump-activity/sugargame/event.py", line 112, in _quit_cb
    pygame.event.post(pygame.event.Event(pygame.QUIT))
pygame.error: Event queue full
Traceback (most recent call last):
  File "/home/ibiam/Activities/sonic-jump-activity/sugargame/event.py", line 109, in _screen_changed_cb
    self.update_display()
  File "/home/ibiam/Activities/sonic-jump-activity/sugargame/event.py", line 98, in update_display
    pygame.event.post(pygame.event.Event(pygame.VIDEOEXPOSE))
pygame.error: Event queue full
```

@sparshg you might want to take a look at this.

**Comment by sparshg** [comment]
> Resuming an activity instance

How do I pause the activity to reproduce this?

**Comment by chimosky** [comment]
> How do I pause the activity to reproduce this?

Resuming an activity instance is basically starting an activity and ending it then resuming same instance from the journal or from the home view.

**Comment by sparshg** [comment]
So I tried to start the game, pressed Alt-Tab to switch to journal and again to get back to activity, but it didn't crash for me (on live build).

**Comment by chimosky** [comment]
Tested again and it doesn't happen again, I'll leave this open for now as it's not clear why it happened the first time and I don't think the issue has been fixed.

**Comment by chimosky** [comment]
Closing as the issue has been fixed.
